# Generated by Django 5.2.7 on 2025-10-21 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='booktranslation',
            options={'verbose_name': 'Перевод книги', 'verbose_name_plural': 'Переводы книг'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['key'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='categorytranslation',
            options={'verbose_name': 'Перевод категории', 'verbose_name_plural': 'Переводы категорий'},
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(upload_to='books/pdfs/%Y/%m/%d/', verbose_name='PDF файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='booktranslation',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='booktranslation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='booktranslation',
            name='description',
            field=models.TextField(verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='booktranslation',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ky', 'Кыргызча')], max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='booktranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='category',
            name='key',
            field=models.SlugField(unique=True, verbose_name='Ключ категории'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ky', 'Кыргызча')], max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
    ]
