# Generated by Django 5.2.7 on 2025-10-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_remove_category_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktranslation',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык'),
        ),
    ]
